sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tharakanwn2014/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true tharakanwn2014/docker-react npm run test