sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tharakanwn2014/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true tharakanwn2014/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-525635930965"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"